Ashirvad-main/Ashirvad.Web/Controllers/UserRightsController.cs
using Ashirvad.Common;
using Ashirvad.Data;
using Ashirvad.Data.Model;
using Ashirvad.ServiceAPI.ServiceAPI.Area.Page;
using Ashirvad.ServiceAPI.ServiceAPI.Area.UserRights;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using static Ashirvad.Common.Common;

namespace Ashirvad.Web.Controllers
{
    public class UserRightsController : BaseController
    {
        // GET: UserRights
        private readonly IUserRightsService _UserRightService;
        private readonly IPageService _pageService;

        public UserRightsController(IUserRightsService UserRightService, IPageService pageService)
        {

            _UserRightService = UserRightService;
            _pageService = pageService;
        }

        // GET: UserRight
        public ActionResult Index()
        {

            return View();
        }

        public async Task<ActionResult> UserRightMaintenance(long UserRightID)
        {
            UserWiseRightMaintenanceModel UserRight = new UserWiseRightMaintenanceModel();
            UserRight.UserWiseRightInfo = new UserWiseRightsEntity();
            //var UserRightData = await _UserRightService.GetAllUserRightss();
            UserRight.UserWiseRightData = new List<UserWiseRightsEntity>();

            if (UserRightID > 0)
            {
                var result = await _UserRightService.GetUserRightsByID(UserRightID);
                var UserRightData1 = await _UserRightService.GetAllUserRightsUniqData(result.Roleinfo.RoleID);
                UserRight.UserWiseRightInfo = result;
                UserRight.UserWiseRightInfo.list = UserRightData1;

            }

            var UserData = await _pageService.GetAllPages(SessionContext.Instance.LoginUser.BranchInfo.BranchID);
            UserRight.UserWiseRightInfo.PageList = UserData;
            return View("Index", UserRight);
        }

        [HttpPost]
        public async Task<JsonResult> SaveUserRight(UserWiseRightsEntity UserRight)
        {

            UserWiseRightsEntity UserRightEntity = new UserWiseRightsEntity();
            ResponseModel responseModel = new ResponseModel();
            UserRight.Transaction = GetTransactionData(UserRight.UserWiseRightsID > 0 ? Common.Enums.TransactionType.Update : Common.Enums.TransactionType.Insert);
            UserRight.RowStatus = new RowStatusEntity()
            {
                RowStatusId = (int)Enums.RowStatus.Active
            };
            if (UserRight.UserID == 0)
            {
                UserRight.UserID = UserRight.userinfo.UserID;
            }
            responseModel = await _UserRightService.UserRightsMaintenance(UserRight);


            return Json(responseModel);
        }

        [HttpPost]
        public JsonResult RemoveUserRight(long UserRightID)
        {
            var result = _UserRightService.RemoveUserRights(UserRightID, SessionContext.Instance.LoginUser.Username);
            return Json(result);
        }

        public async Task<JsonResult> UserRightData()
        {
            var UserRightData = await _UserRightService.GetAllUserRightss();

            return Json(UserRightData);
        }

        public async Task<ActionResult> UserRightUniqueData(long RoleRightID)
        {
            var UserRightData = await _UserRightService.GetAllUserRightsUniqData(RoleRightID);

            return View("~/Views/UserRights/RightsDataTable.cshtml", UserRightData);
        }

        public async Task<JsonResult> CustomServerSideSearchAction(DataTableAjaxPostModel model)
        {
            var UserData = await _UserRightService.GetAllCustomRights(model,SessionContext.Instance.LoginUser.BranchInfo.BranchID);
            long total = 0;
            if (UserData.Count > 0)
            {
                total = UserData[0].Count;
            }
            return Json(new
            {
                draw = model.draw,
                iTotalRecords = total,
                iTotalDisplayRecords = total,
                data = UserData
            });

        }
    }
}

Ashirvad-main/Ashirvad.Web/Views/UserRights/Create.cshtml
@model Ashirvad.Data.UserWiseRightsEntity
<div class="col-md-12">
    <form id="fRoleRightDetail">


        @*@if (SessionContext.Instance.LoginUser.UserType == Ashirvad.Common.Enums.UserType.SuperAdmin)
        {
            <div class="col-md-4">
                @Html.Label("Branch", htmlAttributes: new { @class = "control-label" })<span style="color:red">*</span>
                <select name="BranchName" id="BranchName" class="form-control requiredDDL" alt="Branch">
                    <option value="0">--Select Branch--</option>
                </select>
                @Html.HiddenFor(x=>x.branchinfo.BranchID)
            </div>
        }*@

    <div class="col-md-4" id="drights">
        @Html.Label("User", htmlAttributes: new { @class = "control-label" })<span style="color:red">*</span>
        <select name="UserName" id="UserName" class="form-control requiredDDL" alt="User">
            <option value="0">--Select User--</option>
        </select>
        @Html.HiddenFor(x => x.userinfo.UserID)
        @Html.HiddenFor(x=>x.UserWiseRightsID)
    </div>
        <div class="col-md-4" id="drights">
            @Html.Label("Role", htmlAttributes: new { @class = "control-label" })<span style="color:red">*</span>
            <select name="RoleName" id="RoleName" class="form-control requiredDDL" alt="Role">
                <option value="0">--Select Role--</option>
             @Html.HiddenFor(x=>x.Roleinfo.RoleID)
            </select>
        </div>
        <div class="form-group">
            <div class="col-md-4" style="text-align: right;">
                <br />
                <a onclick="return SaveUserWiseRight();" class="ladda-button mb-2 mr-2 btn btn-primary" data-style="expand-left">
                    <span class="ladda-label">
                        Save
                    </span>
                    <span class="ladda-spinner"></span>
                </a>
                <a href="@Url.Action("UserRightMaintenance","UserRights", new { @UserRightID=0 })" class="ladda-button mb-2 mr-2 btn btn-danger" data-style="expand-left">
                    <span class="ladda-label">
                        Cancel
                    </span>
                    <span class="ladda-spinner"></span>
                </a>
            </div>
        </div>
    </form>
</div>
<div class="course" id="UserDetails">

</div>
<div class="col-md-12">
    <div id="rightsdiv" style="max-height: 200px; overflow-y: scroll !important">
        @{
            Html.RenderPartial("RightsDataTable", new ViewDataDictionary(Model.list));

        }
    </div>
</div>

Ashirvad-main/Ashirvad.Web/Views/UserRights/Index.cshtml
@model Ashirvad.Data.Model.UserWiseRightMaintenanceModel
@{
    ViewBag.Title = "User Wise Right";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content">
    <div class="messagealert" id="alert_container"></div>
    <div class="row">
        <section class="col-md-6">
            <div class="box box-warning">
                <div class="box-header with-border">
                    <h3 class="box-title">User Wise Right Entry</h3>
                </div>
                <div class="box-body">
                    @{
                        Html.RenderPartial("Create", new ViewDataDictionary(Model.UserWiseRightInfo));
                    }
                </div>
            </div>
        </section>
        <section class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="col-md-6">User Wise Right Details</h3>

                    @{
                        Html.RenderPartial("Manage", new ViewDataDictionary(Model.UserWiseRightData));
                    }
                </div>
            </div>
        </section>
    </div>

    @section Scripts {
        @*<script src="~/ThemeData/plugins/jQuery/jquery-2.2.3.min.js"></script>*@
        <script src="~/ThemeData/plugins/datatables/jquery.dataTables.min.js"></script>
        <script src="~/ThemeData/plugins/datatables/dataTables.bootstrap.min.js"></script>
        <script src="~/scripts/app/userwiserights.js"></script>
        <script>
            $('#choiceList').DataTable({
                "bPaginate": false,
                "bLengthChange": false,
                "bFilter": false,
                "bInfo": false,
                "bAutoWidth": true
            });
            //$('#branchrightstable').DataTable({
            //    "bPaginate": true,
            //    "bLengthChange": false,
            //    "bFilter": true,
            //    "bInfo": false,
            //    "bAutoWidth": true
            //});
        </script>
        <script type="text/javascript">
            function ConfirmationDialog() {
                if (confirm("Are you sure to continue?"))
                    return true;
                else
                    return false;
            }
        </script>

    }

</section>

Ashirvad-main/Ashirvad.Web/Views/UserRights/Manage.cshtml
<table style="width: 100%;" id="userrightstable" class="table table-striped dataTable no-footer">
    <thead>
        <tr style="background-color:#005cbf;font-style:inherit;color:aliceblue">
            <th style="width:5%">Module Details</th>
            <th>
                User Name
            </th>
            <th>
                Role
            </th>

            <th>
                Edit
            </th>
            <th>
                Delete
            </th>
        </tr>
    </thead>
    <tbody>
        @*@for (var item = 1; item < 4; item++)
        {
        <tr>
            <td>

                <img src="~/ThemeData/images/plus.png" height="20" />
                <div style="display:none">
                    <div style="max-height: 200px; overflow-y: scroll !important">
                        <table style="width: 100%;" id="subcategorytbl2" class="table table-bordered dataTable no-footer">
                            <thead>
                                <tr style="background-color:#005cbf;font-style:inherit;color:aliceblue">

                                    <th>
                                        Page
                                    </th>
                                    <th>
                                        Create Status
                                    </th>

                                    <th>
                                        Delete Status
                                    </th>
                                    <th>
                                        View Status
                                    </th>

                                </tr>
                            </thead>

                            <tbody>
                                @for (var i = 1; i < 21; i++)
                                {

                                    <tr>


                                        <td>
                                            Page @i
                                        </td>
                                        <td>
                                            True
                                        </td>

                                        <td>
                                            True
                                        </td>
                                        <td>
                                            True
                                        </td>
                                    </tr>

                                }
                            </tbody>



                        </table>
                    </div>

                </div>
            </td>
            <td>
                User @item
            </td>
            <td>
                Role 1
            </td>

            <td>
                <a href="#">
                    <img src="/ThemeData/images/viewIcon.png" />
                </a>
            </td>

            <td>
                <a href="#">
                    <img src="~/ThemeData/images/Delete.png" />
                </a>
            </td>

        </tr>
        }*@
    </tbody>

</table>

<script type="text/javascript">
    //Assign Click event to Plus Image.

    $("body").on("click", "img[src*='plus.png']", function () {
        $(this).closest("tr").after("<tr><td></td><td colspan = '999'>" + $(this).next().html() + "</td></tr>");
        $(this).attr("src", "../ThemeData/images/minus.png");
    });
    //Assign Click event to Minus Image.
    $("body").on("click", "img[src*='minus.png']", function () {
        $(this).attr("src", "../ThemeData/images/plus.png");
        $(this).closest("tr").next().remove();
    });
</script>

Ashirvad-main/Ashirvad.Web/Views/UserRights/RightsDataTable.cshtml
@using Ashirvad.Web.Controllers;
@model List<Ashirvad.Data.UserWiseRightsEntity>
@{
    Layout = null;
}

<table style="width: 100%;" id="choiceList" class="table table-striped dataTable no-footer">
    <thead>
        <tr style="background-color:#005cbf;font-style:inherit;color:aliceblue">

            <th>
                Module
            </th>
            <th>
                Create Status
            </th>

            <th>
                Delete Status
            </th>
            <th>
                View Status
            </th>

        </tr>
    </thead>

    <tbody>
        @foreach (var item1 in Model)
        {
            <tr>
                <td>
                    @item1.PageInfo.Page
                </td>
                    @if (@item1.RoleRightinfo.Createstatus == true)
                    {
                    <td>

                        Yes

                    </td>
                }
                else
                {
                    <td>

                        No

                    </td>
                }
                    @if (@item1.RoleRightinfo.Deletestatus == true)
                    {
                        <td>

                            Yes

                        </td>
                    }
                    else
                    {
                        <td>

                            No

                        </td>
                    }
                    @if (@item1.RoleRightinfo.Viewstatus == true)
                    {
                        <td>

                            Yes

                        </td>
                    }
                    else
                    {
                        <td>

                            No

                        </td>
                    }

                </tr>
            }
    </tbody>
</table>