Ashirvad-main/Ashirvad.Web/Controllers/WinnerEntryController.cs
using Ashirvad.Common;
using Ashirvad.Data;
using Ashirvad.Data.Model;
using Ashirvad.ServiceAPI.ServiceAPI.Area.Branch;
using Ashirvad.ServiceAPI.ServiceAPI.Area.Competiton;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Ashirvad.Web.Controllers
{
    public class WinnerEntryController : BaseController
    {
        // GET: WinnerEntry
        private readonly ICompetitonService _competitonService;
        private readonly IBranchService _branchService;
        public WinnerEntryController(ICompetitonService competitonService, IBranchService branchService)
        {
            _competitonService = competitonService;
            _branchService = branchService;
        }
        public ActionResult Index()
        {
            CompetitonMaintenanceModel competitonMaintenanceModel = new CompetitonMaintenanceModel();
            competitonMaintenanceModel.competitionWinnerEntity = new CompetitionWinnerEntity();
            competitonMaintenanceModel.competitionWinnerData = new List<CompetitionWinnerEntity>();
            return View(competitonMaintenanceModel);
        }
        public async Task<ActionResult> CompetitionWinnerMaintenance(long CompetitionWinnerId)
        {
            CompetitonMaintenanceModel competitonMaintenanceModel = new CompetitonMaintenanceModel();
            competitonMaintenanceModel.competitionWinnerEntity = new CompetitionWinnerEntity();
            competitonMaintenanceModel.competitionWinnerData = new List<CompetitionWinnerEntity>();
            if (CompetitionWinnerId > 0)
            {
                var data = await _competitonService.GetCompetitionWinnerDetailbyId(CompetitionWinnerId);
                competitonMaintenanceModel.competitionWinnerEntity = data.Data;
            }
            var da = await _competitonService.GetCompetitionWinnerListbyCompetitionId();
            competitonMaintenanceModel.competitionWinnerData = da.Data;
            return View("Index", competitonMaintenanceModel);
        }
        public async Task<JsonResult> GetStudentListbyCompetitionIdandBranchId(long CompetitionId, long BranchId)
        {
            var result = await _competitonService.GetCompetitionRankListByCompetitionIdandBranchID(CompetitionId, BranchId);
            return Json(result);
        }
        public async Task<JsonResult> GetBranchList()
        {
            var branchData = await _branchService.GetAllBranch();
            return Json(branchData);
        }
        public async Task<JsonResult> GetCompetitionList()
        {
            var result = _competitonService.GetAllCompetitonData();
            return Json(result);
        }

        public async Task<JsonResult> SaveCompetitionWinner(CompetitionWinnerEntity winnerEntity)
        {
            winnerEntity.RowStatus = new RowStatusEntity()
            {
                RowStatusId = (int)Enums.RowStatus.Active
            };
            winnerEntity.Transaction = GetTransactionData(winnerEntity.competition_winner_id > 0 ? Common.Enums.TransactionType.Update : Common.Enums.TransactionType.Insert);
            var data = await _competitonService.CompetitionWinnerMaintenance(winnerEntity);
            return Json(data);
        }
        public async Task<JsonResult> RemoveCompetitionWinner(long CompetitionWinnerId)
        {
           var data = await _competitonService.DeleteCompetitionWinner(CompetitionWinnerId,SessionContext.Instance.LoginUser.Username);
            return Json(data);
        }

    }
}

Ashirvad-main/Ashirvad.Web/Views/WinnerEntry/Create.cshtml
@model Ashirvad.Data.CompetitionWinnerEntity
<form id="fCompetitionWinner">
    <div class="form-group" id="dInformation">
        <div class="col-md-12">
            @Html.Label(" Select Competition", htmlAttributes: new { @class = "control-label" })<span style="color:red">*</span>
            <select name="Comp" id="Comp" class="form-control requiredDDL select2" alt="Competition">
                <option value="0">--Select Competition--</option>
                @Html.HiddenFor(x => x.competitionInfo.CompetitionID)
                @Html.HiddenFor(x => x.competition_winner_id)
            </select>
        </div>
        <div class="col-md-12">
            @Html.Label(" Select Branch", htmlAttributes: new { @class = "control-label" })<span style="color:red">*</span>
            <select name="Branch" id="Branch" class="form-control requiredDDL select2" alt="Branch">
                <option value="0">--Select Branch--</option>
                @Html.HiddenFor(x => x.competitionRankInfo.branchInfo.BranchID)
            </select>
        </div>
        <div class="col-md-12">
            @Html.Label(" Select Student", htmlAttributes: new { @class = "control-label" })<span style="color:red">*</span>
            <select name="Student" id="Student" class="form-control requiredDDL select2" alt="Student">
                <option value="0">--Select Student--</option>
                @Html.HiddenFor(x => x.competitionRankInfo.CompetitionRankId)
            </select>
        </div>
        <div class="col-md-12">
            @Html.Label("Prize Name", htmlAttributes: new { @class = "control-label" })<span style="color:red">*</span>
            @Html.TextBoxFor(x => x.prizeName, null, new { @class = "form-control required ", @alt = "Prize Name", autocomplete = "off" })
        </div>

        <div class="form-group">
            <div class="col-md-12" style="text-align: right;">
                <br />
                <a onclick="SaveCompetitionWinner();" class="ladda-button mb-2 mr-2 btn btn-primary" data-style="expand-left">
                    <span class="ladda-label">
                        Save
                    </span>
                    <span class="ladda-spinner"></span>
                </a>
            </div>
        </div>
    </div>
</form>

Ashirvad-main/Ashirvad.Web/Views/WinnerEntry/Index.cshtml
@model Ashirvad.Data.Model.CompetitonMaintenanceModel
@{
    ViewBag.Title = "Competition Winner Entry";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content">
    <div class="messagealert" id="alert_container"></div>
    <div class="row">
        <section class="col-md-5">
            <div class="box box-warning">
                <div class="box-header with-border">
                    <h3 class="box-title">Winner Entry</h3>
                </div>
                <div class="box-body">
                    @{
                        Html.RenderPartial("Create", new ViewDataDictionary(Model.competitionWinnerEntity));
                    }
                </div>
            </div>
        </section>
        <section class="col-md-7">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="col-md-6">Winner Details</h3>
                    @{
                        Html.RenderPartial("Manage", new ViewDataDictionary(Model.competitionWinnerData));
                    }
                </div>
            </div>
        </section>
    </div>
    @section Scripts {
       
        <script type="text/javascript" src="~/scripts/app/competitionWinner.js"></script>
        @*<script src="~/ThemeData/plugins/jQuery/jquery-2.2.3.min.js"></script>*@
        <script src="~/ThemeData/plugins/datatables/jquery.dataTables.min.js"></script>
        <script src="~/ThemeData/plugins/datatables/dataTables.bootstrap.min.js"></script>
        <script>
                $(document).ready(function () {

                    $('#studenttbl').DataTable({
                        "bPaginate": true,
                        "bLengthChange": false,
                        "bFilter": true,
                        "bInfo": true,
                        "bAutoWidth": true
                    });
                });
            </script>
        <script type="text/javascript">
            function ConfirmationDialog() {
                if (confirm("Are you sure to continue?"))
                    return true;
                else
                    return false;
            }
        </script>
    }
</section>

Ashirvad-main/Ashirvad.Web/Views/WinnerEntry/Manage.cshtml
@using Ashirvad.Web.Controllers;
@model List<Ashirvad.Data.CompetitionWinnerEntity>
<table style="width: 100%;" id="studenttbl" class="table table-striped dataTable no-footer">
    <thead>
        <tr style="background-color:#005cbf;font-style:inherit;color:aliceblue">
            <th>
                Competiton Name
            </th>
            <th>
                Prize
            </th>
            <th>
                Branch
            </th>
            <th>
                Course
            </th>
            <th>
                Class
            </th>
            <th>
                Student
            </th>
            <th>
                Edit
            </th>
            <th>
                Delete
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model?.Count > 0) { 
        foreach(var item in Model)
                {
                    <tr>
                        <td>
                            @item.competitionInfo.CompetitionName
                        </td>
                        <td>
                            @item.prizeName
                        </td>
                        <td>
                            @item.competitionRankInfo.branchInfo.BranchName
                        </td>
                        <td>
                            @item.competitionRankInfo.studentInfo.BranchClass.BranchCourse.course.CourseName
                        </td>
                        <td>
                            @item.competitionRankInfo.studentInfo.BranchClass.Class.ClassName
                        </td>
                        <td>
                            @item.competitionRankInfo.studentInfo.FirstName @item.competitionRankInfo.studentInfo.LastName
                        </td>
                        <td>
                            <a href="@Url.Action("CompetitionWinnerMaintenance", "WinnerEntry", new { CompetitionWinnerId = item.competition_winner_id })">
                                <img src="~/ThemeData/images/viewIcon.png" />
                            </a>
                        </td>
                        <td>
                            <a style="margin-left:20px;" href="#" onclick="RemoveCompetitionWinner(@item.competition_winner_id);">
                                <img src="~/ThemeData/images/delete.png" />
                            </a>
                        </td>
                    </tr>
                }
        }
    </tbody>

</table>