Ashirvad-main/Ashirvad.Web/Controllers/FacultyController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Ashirvad.Common;
using Ashirvad.Data;
using Ashirvad.Data.Model;
using Ashirvad.ServiceAPI.ServiceAPI.Area.Faculty;
using Newtonsoft.Json;
using static Ashirvad.Common.Common;

namespace Ashirvad.Web.Controllers
{
    public class FacultyController : BaseController
    {
        private readonly IFacultyService _facultyService;
        public FacultyController(IFacultyService facultyService)
        {
            _facultyService = facultyService;
        }
        // GET: Faculty
        public ActionResult Index()
        {
           
            return View();
        }

        public async Task<ActionResult> FacultyMaintenance(long facultyID)
        {
            FacultyMaintenanceModel faculty = new FacultyMaintenanceModel();
            if (facultyID > 0)
            {
                var result = await _facultyService.GetFacultyByFacultyID(facultyID);
                faculty.FacultyInfo = result.Data;
            }
            else
            {
                faculty.FacultyInfo = new FacultyEntity();
            }

            //var branchData = await _facultyService.GetAllFaculty(SessionContext.Instance.LoginUser.BranchInfo.BranchID);
            faculty.FacultyData = new List<FacultyEntity>();

            return View("Index", faculty);
        }

        [HttpPost]
        public async Task<JsonResult> SaveFaculty(FacultyEntity facultyEntity)
        {
            if (facultyEntity.FileInfo != null)
            {
                string _FileName = Path.GetFileName(facultyEntity.FileInfo.FileName);
                string extension = System.IO.Path.GetExtension(facultyEntity.FileInfo.FileName);
                string randomfilename = Common.Common.RandomString(20);
                string _Filepath = "/FacultyImage/" + randomfilename + extension;
                string _path = Path.Combine(Server.MapPath("~/FacultyImage"), randomfilename + extension);
                facultyEntity.FileInfo.SaveAs(_path);
                facultyEntity.FacultyContentFileName = _FileName;
                facultyEntity.FilePath = _Filepath;
            }

            facultyEntity.Transaction = GetTransactionData(facultyEntity.FacultyID > 0 ? Common.Enums.TransactionType.Update : Common.Enums.TransactionType.Insert);
            facultyEntity.RowStatus = new RowStatusEntity()
            {
                RowStatusId = (int)Enums.RowStatus.Active
            };
            var data = await _facultyService.FacultyMaintenance(facultyEntity);
          
            return Json(data);
        }

        [HttpPost]
        public JsonResult RemoveFaculty(long facultyID)
        {
            var result = _facultyService.RemoveFaculty(facultyID, SessionContext.Instance.LoginUser.Username);
            return Json(result);
        }

        public async Task<JsonResult> CustomServerSideSearchAction(DataTableAjaxPostModel model)
        {
            var branchData = await _facultyService.GetAllCustomFaculty(model,SessionContext.Instance.LoginUser.BranchInfo.BranchID);
            long total = 0;
            if (branchData.Count > 0)
            {
                total = branchData[0].Count;
            }
            return Json(new
            {
                // this is what datatables wants sending back
                draw = model.draw,
                iTotalRecords = total,
                iTotalDisplayRecords = total,
                data = branchData
            });

        }
        [HttpPost]
        public async Task<ActionResult> GetExportData(string Search)
        {
            var branchData = await _facultyService.GetAllFaculty(SessionContext.Instance.LoginUser.BranchInfo.BranchID);
            return View("~/Views/Faculty/_Export_Faculty.cshtml", branchData);

        }
    }
}

Ashirvad-main/Ashirvad.Web/Views/Faculty/Create.cshtml
@model Ashirvad.Data.FacultyEntity
<form id="ffacultydetail">
    <div class="form-group" id="dInformation">
        @if (SessionContext.Instance.LoginUser.UserType == Ashirvad.Common.Enums.UserType.SuperAdmin)
        {
            <div class="col-md-12">
                @Html.Label("Select Branch", htmlAttributes: new { @class = "control-label" })<span style="color:red">*</span>
                <select name="BranchName" id="BranchName" class="form-control requiredDDL select2" alt="Branch">
                    <option value="0">--Select Branch--</option>
                </select>
                @Html.HiddenFor(x => x.BranchInfo.BranchID)
            </div>
        }
        else
        {
            <div class="col-md-12" style="display: none;">
                @Html.Label("Select Branch", htmlAttributes: new { @class = "control-label" })<span style="color:red">*</span>
                <select name="BranchName" id="BranchName" class="form-control" alt="Branch">
                    <option value="0">--Select Branch--</option>
                </select>
                @Html.HiddenFor(x => x.BranchInfo.BranchID)
            </div>
        }

            <div class="col-md-12" style="margin-bottom:7px;">
                @Html.Label("Select Faculty", htmlAttributes: new { @class = "control-label" })<span style="color:red">*</span>
                <select name="facultyName" id="facultyName" class="form-control requiredDDL select2" alt="Faculty Name">
                    <option value="0">--Select Faculty--</option>

                </select>
                @Html.HiddenFor(x => x.staff.StaffID)
                @Html.HiddenFor(x => x.BranchInfo.BranchID)
                @Html.HiddenFor(x => x.FacultyID)                
            </div>
        <div>
            <div class="col-md-6">
                @Html.Label("Course Name", htmlAttributes: new { @class = "control-label" })<span style="color:red">*</span>
                <select name="CourseName" id="CourseName" class="form-control requiredDDL" alt="Course Name">
                    <option value="0">--Select Course Name--</option>
                </select>
                @Html.HiddenFor(x => x.BranchCourse.course_dtl_id)
            </div>
            <div class="col-md-6">
                @Html.Label("Class Name", htmlAttributes: new { @class = "control-label" })<span style="color:red">*</span>
                <select name="ClassName" id="ClassName" class="form-control requiredDDL" alt="Class Name">
                    <option value="0">--Select Class Name--</option>
                </select>
                @Html.HiddenFor(x => x.BranchClass.Class_dtl_id)
            </div>
        </div>
        <div class="col-md-6" style="margin-bottom:7px;">
            @Html.Label("Select Subject", htmlAttributes: new { @class = "control-label" })<span style="color:red">*</span>
            <select name="SubjectName" id="SubjectName" class="form-control requiredDDL" alt="Subject Name">
                <option value="0">--Select Subject--</option>

            </select>
            @Html.HiddenFor(x => x.branchSubject.Subject_dtl_id)
        </div>
        <div class="col-md-6" style="margin-bottom:7px;">
            @Html.Label("Faculty Image", htmlAttributes: new { @class = "control-label" })<span style="color:red">*</span>
            <input class="file-upload fileRequired" alt="Header Image" id="fuHeaderImageDetail" name="ImageFile" type="file" accept="image/*" />
            @Html.HiddenFor(x => x.HeaderImageText)
            @Html.HiddenFor(x => x.FileInfo)
            @Html.HiddenFor(x => x.FilePath)
            @Html.HiddenFor(x => x.FacultyContentFileName)
        </div>

        <div class="col-md-12">
            @Html.Label("Description", htmlAttributes: new { @class = "control-label" })<span style="color:red">*</span>
            @Html.TextAreaFor(x => x.Descripation, new { @class = "form-control required", autocomplete = "off", @alt = "Description" })

        </div>        
        <div class="form-group">
            <div class="col-md-12" style="text-align: right;margin-top:10px;">
                <a onclick="return SaveFaculty();" class="ladda-button mb-2 mr-2 btn btn-primary" data-style="expand-left">
                    <span class="ladda-label">
                        Save
                    </span>
                    <span class="ladda-spinner"></span>
                </a>
                <a href="@Url.Action("FacultyMaintenance","Faculty", new { @facultyID=0 })" class="ladda-button mb-2 mr-2 btn btn-danger" data-style="expand-left">
                    <span class="ladda-label">
                        Cancel
                    </span>
                    <span class="ladda-spinner"></span>
                </a>
            </div>
        </div>

    </div>
</form>

Ashirvad-main/Ashirvad.Web/Views/Faculty/Index.cshtml
@model Ashirvad.Data.Model.FacultyMaintenanceModel
@{
    ViewBag.Title = "Faculty";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<section class="content">
    <div class="row">
        <div class="messagealert" id="alert_container"></div>
        <section class="col-md-5">
            <div class="box box-warning">
                <div class="box-header with-border">
                    <h3 class="box-title h3">Faculty Entry</h3>
                </div>
                <div class="box-body">
                    @{
                        Html.RenderPartial("Create", new ViewDataDictionary(Model.FacultyInfo));
                    }
                </div>
            </div>
        </section>
        <section class="col-md-7">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="col-md-6 h3" id="exceltitle">Faculty Details</h3>
                    <button type="button" onclick="Exportdata('Faculty')" class="btn btn-success"><i class="fa fa-file-excel-o" style="color:white"></i>  Export</button>
                    @{
                        Html.RenderPartial("Manage", new ViewDataDictionary(Model.FacultyData));
                    }
                </div>
            </div>
        </section>
    </div>
    @section Scripts {
        @*<script src="~/ThemeData/plugins/jQuery/jquery-2.2.3.min.js"></script>*@
        <script src="~/ThemeData/plugins/datatables/jquery.dataTables.min.js"></script>
        <script src="~/ThemeData/plugins/datatables/dataTables.bootstrap.min.js"></script>
        <script type="text/javascript" src="~/scripts/app/faculty.js"></script>
        @*<script>
            $(document).ready(function () {

                $('#studenttbl').DataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": true,
                    "bInfo": true,
                    "bAutoWidth": true
                });
            });
        </script>*@
        <script type="text/javascript">
            function ConfirmationDialog() {
                if (confirm("Are you sure to continue?"))
                    return true;
                else
                    return false;
            }
        </script>
    }
</section>

Ashirvad-main/Ashirvad.Web/Views/Faculty/Manage.cshtml
@model List<Ashirvad.Data.FacultyEntity>

<table style="width: 100%;" id="facultytable" class="table table-striped dataTable no-footer">
    <thead>
        <tr style="background-color:#005cbf;font-style:inherit;color:aliceblue">

            <th>
                Faculty Name
            </th>
            <th>
                Faculty Image
            </th>
            <th>
                Course Name
            </th>
            <th>
                Standard
            </th>
            <th>
                Subject
            </th>
            <th class="FacultyMasterCreate">
                Edit
            </th>
            <th class="FacultyMasterDelete">
                Delete
            </th>
        </tr>
    </thead>
    <tbody></tbody>
    
</table>

Ashirvad-main/Ashirvad.Web/Views/Faculty/_Export_Faculty.cshtml
@model List<Ashirvad.Data.FacultyEntity>

@{
    Layout = null;
}

<table class="table" style="border: 1px groove black; border-collapse: collapse;">
    <tr>
        <th style="border: 1px groove black; border-collapse: collapse;">
            Select Faculty
        </th>
        <th style="border: 1px groove black; border-collapse: collapse;">
            Course Name
        </th>
        <th style="border: 1px groove black; border-collapse: collapse;">
            Class  Name
        </th>
        <th style="border: 1px groove black; border-collapse: collapse;">
            Select Subject
        </th>
        <th style="border: 1px groove black; border-collapse: collapse;">
            Description
        </th>
       
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td style="border: 1px groove black; border-collapse: collapse;">
        @item.staff.Name
    </td>
    <td style="border: 1px groove black; border-collapse: collapse;">
        @item.BranchCourse.course.CourseName
    </td>
    <td style="border: 1px groove black; border-collapse: collapse;">
        @item.BranchClass.Class.ClassName
    </td>
    <td style="border: 1px groove black; border-collapse: collapse;">
        @item.branchSubject.Subject.SubjectName
    </td>
    <td style="border: 1px groove black; border-collapse: collapse;">
        @item.Descripation
    </td>
    
</tr>
    }

</table>