Ashirvad-main/Ashirvad.Web/Controllers/ChangePasswordController.cs
using Ashirvad.Repo.DataAcceessAPI.Area.User;
using Ashirvad.ServiceAPI.ServiceAPI.Area.User;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ashirvad.Web.Controllers
{
    public class ChangePasswordController : Controller
    {
        private readonly IUserService _userServices;

        public ChangePasswordController(IUserService staffService)
        {
            _userServices = staffService;
        }
        // GET: ChangePassword
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult changepassword(string password, string oldPassword)
        {
            var result = _userServices.ChangePassword(SessionContext.Instance.LoginUser.UserID, password,oldPassword).Result;
            return Json(result);
        }
    }
}

Ashirvad-main/Ashirvad.Web/Views/ChangePassword/Index.cshtml
@model Ashirvad.Data.UserEntity
@{
    ViewBag.Title = "Change Password";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<section class="content">
    <div class="messagealert" id="alert_container"></div>
    <script type="text/javascript" src='~/scripts/app/common.js'></script>
    <script type="text/javascript" src='~/Scripts/ashirvad.js'></script>
    <div class="row">
        <div class="col-md-7" style="padding-left:35%">
            <div class="box box-warning" style="width:500px;padding:10px">
                <div class="box-header with-border">
                    <h3 class="box-body">Change PassWord</h3>
                </div>
                <div class="box-body">
                    <div class="form-group">
                        <asp:ValidationSummary ID="ValidationSummary1" runat="server" />
                    </div>
                    <form id="fchangepassword">
                        <div class="row" id="dInformation">
                            <div class="form-group">
                                <div class="col-md-12">
                                    @Html.Label("Old Password", htmlAttributes: new { @class = "control-label" })<span style="color:red">*</span>
                                    @Html.Password("OldPwd", null, new { @Id = "old_password", @class = "form-control required", autocomplete = "off", @alt = " Old Password" })
                                </div>
                                <div class="col-md-12">
                                    @Html.Label("New Password", htmlAttributes: new { @class = "control-label" })<span style="color:red">*</span>
                                    @Html.Password("NewPwd", null, new { @Id = "new_password", @class = "form-control required", autocomplete = "off", @alt = " New Password" })
                                </div>
                                <div class="col-md-12">
                                    @Html.Label("Confirm Password", htmlAttributes: new { @class = "control-label" })<span style="color:red">*</span>
                                    @Html.PasswordFor(x => x.Password, new { @Id = "confirm_password", @class = "form-control required", autocomplete = "off", @alt = "Confirm Password" })
                                    @Html.HiddenFor(x => x.UserID)
                                </div>
                                <div class="col-md-12" style="text-align: right;margin-top:27px;">
                                    <a href="#" onclick="return ChangePassword();" class="ladda-button mb-2 mr-2 btn btn-primary" data-style="expand-left">
                                        <span class="ladda-label">
                                            Save
                                        </span>
                                        <span class="ladda-spinner"></span>
                                    </a>
                                    <a href="@Url.Action("Index","ChangePassword")" class="ladda-button mb-2 mr-2 btn btn-danger" data-style="expand-left">
                                        <span class="ladda-label">
                                            Cancel
                                        </span>
                                        <span class="ladda-spinner"></span>
                                    </a>

                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="~/scripts/app/login.js"></script>
</section>